### ISSUE TITLE
The flutter onScan method does not return data, but there is a log print available

### ISSUE THREAD

**Issue by lanzhu1993** [nimr77/Flutter_credit_card_scanner#3]
W/qdgralloc( 9912): getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
[log] H-F
[log] biometric
[log] 5412 7512 3412 3456
[log] 12/23
[log] Lee M. Cardholder
[log] mastercard
[log] +
[log] 100%

**Comment by lanzhu1993** [comment]
When everything else is returned as null, only the name is obtained

 [Test Card Image](https://img2.baidu.com/it/u=2287167959,3707264909&fm=253&fmt=auto&app=138&f=JPEG?w=584&h=367)


` void onScanTextML(RecognizedText readText) {
    // Call onScan callback if required information is found
    CreditCardModel? creditCardModel;
    for (TextBlock block in readText.blocks) {
      for (TextLine line in block.lines) {
        if (widget.debug) log(line.text);

        _process.processNumber(line.text);

        _process.processName(line.text);
        _process.processDate(line.text);
        // for (TextElement element in line.elements) {
        //   final text = element.text;

        // }
      }

      creditCardModel = _process.getCreditCardModel();
    }

    if (creditCardModel != null) {
      widget.onScan(context, creditCardModel);
    }
  }`

**Comment by nimr77** [comment]
@lanzhu1993  Hi could you share the parameters of what you set for the widget

**Comment by nimr77** [comment]
I have checked the credit card: 
https://dnschecker.org/credit-card-validator.php?ccn=5412751234123456
it says it's unvalide, since the plugin validates the credit card number to make sure it's a credit number, it rejects the process 

yet I made an update for the Android ML algorithm, I think Apple Vision is better

**Comment by lanzhu1993** [comment]
![image](https://github.com/user-attachments/assets/903ceecb-6472-4aa7-89c7-f249e4839a52)

**Comment by lanzhu1993** [comment]
<img width="1257" alt="image" src="https://github.com/user-attachments/assets/286b1141-db00-447f-b9f0-6b1aa8e960cb">
I have updated to the latest version, flutter_credit_card_stcanner: ^ 0.11.5, but it was recognized on Android. I traced and debugged the code to obtain text, but it was not recognized. In flutter_credit_card_stcanner: ^ 0.11.2, it was recognized but crashed. The specific code is as follows:

![image](https://github.com/user-attachments/assets/4d9d6b9f-5e96-4b52-afec-d1f63fc17a67)
![image](https://github.com/user-attachments/assets/d095ea40-dc89-45fe-b230-855a127c9be3)

**Comment by nimr77** [comment]
ok, I see I have added scanning duration to slow down the frame rate and not to use too much memory on Android, 
on ios the other hand it works fast, and if I set the duration for the next frame to scan to zero, it won't crash unless the camera resolution is too hight, but with the apple version I don't think so

**Comment by nimr77** [comment]
Check the version of +0.11.6

**Comment by lanzhu1993** [comment]
CCV and date cannot be obtained. 
**My output date is as follows:** 

I/flutter ( 8049): entity is : {"number":"3766 5593 6594 917","expirationMonth":"","expirationYear":"","holderName":"Jes Lee"}

**plugin debug log output is as follows：**


I/flutter ( 8049): └───────────────────
[log] flutte
[log] 6
[log] Jeec
[log] D
[log] MOC
[log] he
[log] com/t4139746/387443422-286b1141-db00-447f-b9f0-6blaa8e960cb.png?jwt=eyJhbGcic
[log] American ExpresS
[log] AMEX
[log] Dress
[log] Validate.
[log] date c
[log] 3766 5641 5460 471
[log] Good thru 10/2022
[log] W/w2 892
[log] D
[log] Joshua Anderson
[log] AM
[log] American Express
[log] AMEK
[log] Express
[log] Validate
[log] Validate
[log] 37-
[log] 3766 5593 6594 917
[log] 2
[log] CW/CV
[log] Good thru 7/2025
[log] Jos
[log] CW/cw2 913
[log] Jes Lee
[log] 5
[log] Scanning catched card: CreditCardModel(number: 3766 5593 6594 917, expirationMonth: , expirationYear: , holderName: Jes Lee)

**Comment by nimr77** [comment]
hmm the code of the card don't scan it, but the year and month here have issues of adding another text that's why, anyway, I added a way to extract them

**Comment by nimr77** [comment]
I will close the issue for now, if any issue please report, Thanks
